/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module rv8_alu(a, b, op, carry_in, result, carry_out, zero, negative);
  wire [8:0] _00_;
  wire [8:0] _01_;
  wire [7:0] _02_;
  wire [8:0] _03_;
  wire [7:0] _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire [8:0] _13_;
  wire [8:0] _14_;
  wire [7:0] _15_;
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  input carry_in;
  wire carry_in;
  output carry_out;
  wire carry_out;
  output negative;
  wire negative;
  input [2:0] op;
  wire [2:0] op;
  output [7:0] result;
  wire [7:0] result;
  wire [8:0] tmp;
  output zero;
  wire zero;
  assign _00_ = a + b;
  assign _01_ = _00_ + carry_in;
  assign _02_ = a & b;
  assign zero = ! tmp[7:0];
  assign _03_ = ~ { 8'h00, carry_in };
  assign _04_ = a | b;
  function [8:0] _22_;
    input [8:0] a;
    input [71:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _22_ = b[8:0];
      8'b??????1?:
        _22_ = b[17:9];
      8'b?????1??:
        _22_ = b[26:18];
      8'b????1???:
        _22_ = b[35:27];
      8'b???1????:
        _22_ = b[44:36];
      8'b??1?????:
        _22_ = b[53:45];
      8'b?1??????:
        _22_ = b[62:54];
      8'b1???????:
        _22_ = b[71:63];
      default:
        _22_ = a;
    endcase
  endfunction
  assign tmp = _22_(9'hxxx, { _01_, _14_, 1'h0, _02_, 1'h0, _04_, 1'h0, _15_, a[0], 1'h0, a[7:1], a, 2'h0, b }, { _12_, _11_, _10_, _09_, _08_, _07_, _06_, _05_ });
  assign _05_ = op == 3'h7;
  assign _06_ = op == 3'h6;
  assign _07_ = op == 3'h5;
  assign _08_ = op == 3'h4;
  assign _09_ = op == 3'h3;
  assign _10_ = op == 3'h2;
  assign _11_ = op == 3'h1;
  assign _12_ = ! op;
  assign _13_ = a - b;
  assign _14_ = _13_ - _03_;
  assign _15_ = a ^ b;
  assign carry_out = tmp[8];
  assign negative = tmp[7];
  assign result = tmp[7:0];
endmodule

module rv8_control(clk, rst_n, opcode, operand, flag_z, flag_c, flag_n, flag_ie, nmi_pending, irq_pending, reg_we, mem_rd, mem_wr, alu_op, addr_src, pc_inc, pc_load, pc_branch, flags_we, ptr_inc, ptr_dec
, sp_inc, sp_dec, ir_load0, ir_load1, halt_out, ie_set, ie_clr, skip_set, int_enter, state_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire [2:0] _013_;
  wire [2:0] _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire [2:0] _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire [2:0] _030_;
  wire [2:0] _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire [2:0] _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire [2:0] _047_;
  wire [2:0] _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire [2:0] _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire [2:0] _062_;
  wire [2:0] _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire [2:0] _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire [2:0] _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire [2:0] _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire [2:0] _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire [2:0] _170_;
  wire _171_;
  wire _172_;
  output [2:0] addr_src;
  wire [2:0] addr_src;
  output [2:0] alu_op;
  wire [2:0] alu_op;
  wire branch_taken;
  input clk;
  wire clk;
  input flag_c;
  wire flag_c;
  input flag_ie;
  wire flag_ie;
  input flag_n;
  wire flag_n;
  input flag_z;
  wire flag_z;
  output flags_we;
  wire flags_we;
  output halt_out;
  wire halt_out;
  output ie_clr;
  wire ie_clr;
  output ie_set;
  wire ie_set;
  output int_enter;
  wire int_enter;
  wire int_request;
  output ir_load0;
  wire ir_load0;
  output ir_load1;
  wire ir_load1;
  input irq_pending;
  wire irq_pending;
  wire is_alu;
  wire is_branch;
  wire is_imm;
  wire is_jal;
  wire is_jmp;
  wire is_ldst;
  wire is_pop;
  wire is_ptr;
  wire is_push;
  wire is_ret;
  wire is_shift;
  wire is_skip;
  wire is_system;
  output mem_rd;
  wire mem_rd;
  output mem_wr;
  wire mem_wr;
  wire needs_s2;
  wire [2:0] next_state;
  input nmi_pending;
  wire nmi_pending;
  wire [2:0] op;
  input [7:0] opcode;
  wire [7:0] opcode;
  input [7:0] operand;
  wire [7:0] operand;
  output pc_branch;
  wire pc_branch;
  output pc_inc;
  wire pc_inc;
  output pc_load;
  wire pc_load;
  output ptr_dec;
  wire ptr_dec;
  output ptr_inc;
  wire ptr_inc;
  wire [1:0] reg_field;
  output reg_we;
  wire reg_we;
  input rst_n;
  wire rst_n;
  wire skip_active;
  wire skip_cond;
  reg skip_flag;
  output skip_set;
  wire skip_set;
  output sp_dec;
  wire sp_dec;
  output sp_inc;
  wire sp_inc;
  reg [2:0] state;
  output [2:0] state_out;
  wire [2:0] state_out;
  wire [2:0] unit;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) skip_flag <= 1'h0;
    else if (_112_) skip_flag <= _000_;
  assign _112_ = | { _127_, _126_ };
  assign _113_ = | { _164_, _163_, _121_, _120_ };
  assign _114_ = | { _156_, _119_ };
  assign is_alu = ! opcode[7:5];
  assign is_imm = opcode[7:5] == 3'h1;
  assign is_ldst = opcode[7:5] == 3'h2;
  assign is_branch = opcode[7:5] == 3'h3;
  assign is_shift = opcode[7:5] == 3'h4;
  assign is_ptr = opcode[7:5] == 3'h5;
  assign is_system = opcode[7:5] == 3'h7;
  assign _115_ = opcode[4:3] == 2'h3;
  assign _116_ = ! opcode[1:0];
  assign _117_ = opcode[1:0] == 2'h1;
  assign _118_ = opcode[1:0] == 2'h2;
  assign is_push = opcode == 8'h2c;
  assign is_pop = opcode == 8'h2d;
  assign is_jal = opcode == 8'h3d;
  assign is_ret = opcode == 8'h3e;
  assign is_jmp = opcode == 8'h3c;
  assign _122_ = opcode[4:2] >= 3'h0;
  assign _123_ = opcode[4:2] <= 3'h5;
  assign is_skip = is_branch && _115_;
  assign _124_ = _122_ && _123_;
  assign needs_s2 = is_ldst && _124_;
  assign _125_ = irq_pending && flag_ie;
  assign int_request = _145_ && _138_;
  assign _126_ = skip_set && _138_;
  assign _127_ = _119_ && skip_flag;
  assign _128_ = int_request && _139_;
  assign _129_ = _128_ && _140_;
  assign _130_ = _129_ && _141_;
  assign _131_ = _130_ && _142_;
  assign _132_ = _131_ && _143_;
  assign _133_ = _149_ && _150_;
  assign _134_ = is_branch && _144_;
  assign _135_ = is_ldst && _138_;
  assign _136_ = is_push && _138_;
  assign _137_ = is_pop && _138_;
  assign _139_ = ! needs_s2;
  assign _140_ = ! is_push;
  assign _141_ = ! is_pop;
  assign _142_ = ! is_jal;
  assign _143_ = ! is_ret;
  assign _144_ = ! is_skip;
  assign _138_ = ! skip_flag;
  assign _145_ = nmi_pending || _125_;
  assign _146_ = needs_s2 || is_push;
  assign _147_ = _146_ || is_pop;
  assign _148_ = opcode[4:2] != 3'h5;
  assign _149_ = opcode != 8'h18;
  assign _150_ = opcode != 8'h1c;
  assign _153_ = ~ flag_n;
  assign _151_ = ~ flag_z;
  assign _152_ = ~ flag_c;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state <= 3'h0;
    else state <= next_state;
  assign _107_ = is_ptr ? 1'h0 : _002_;
  assign _108_ = is_ptr ? 1'h0 : _003_;
  assign _106_ = is_ptr ? 1'h0 : _001_;
  assign _102_ = is_jmp ? 1'h1 : 1'h0;
  assign _099_ = is_jmp ? 1'h0 : _107_;
  assign _100_ = is_jmp ? 1'h0 : _108_;
  assign _098_ = is_jmp ? 1'h0 : _106_;
  assign _103_ = is_jmp ? 1'h0 : _109_;
  assign _104_ = is_jmp ? 1'h0 : _110_;
  assign _105_ = skip_cond ? 1'h1 : 1'h0;
  assign _097_ = is_skip ? _105_ : 1'h0;
  assign _089_ = is_skip ? 1'h0 : _099_;
  assign _090_ = is_skip ? 1'h0 : _100_;
  assign _088_ = is_skip ? 1'h0 : _098_;
  assign _094_ = is_skip ? 1'h0 : _103_;
  assign _095_ = is_skip ? 1'h0 : _104_;
  assign _093_ = is_skip ? 1'h0 : _102_;
  assign _092_ = branch_taken ? 1'h1 : 1'h0;
  assign _082_ = _134_ ? _092_ : 1'h0;
  assign _086_ = _134_ ? 1'h0 : _097_;
  assign _079_ = _134_ ? 1'h0 : _089_;
  assign _080_ = _134_ ? 1'h0 : _090_;
  assign _078_ = _134_ ? 1'h0 : _088_;
  assign _084_ = _134_ ? 1'h0 : _094_;
  assign _085_ = _134_ ? 1'h0 : _095_;
  assign _083_ = _134_ ? 1'h0 : _093_;
  assign _077_ = is_shift ? 1'h1 : 1'h0;
  assign _074_ = is_shift ? 1'h0 : _086_;
  assign _066_ = is_shift ? 1'h0 : _079_;
  assign _067_ = is_shift ? 1'h0 : _080_;
  assign _065_ = is_shift ? 1'h0 : _078_;
  assign _071_ = is_shift ? 1'h0 : _084_;
  assign _072_ = is_shift ? 1'h0 : _085_;
  assign _069_ = is_shift ? 1'h0 : _082_;
  assign _070_ = is_shift ? 1'h0 : _083_;
  assign _073_ = _123_ ? 1'h1 : _133_;
  assign _063_ = _123_ ? 3'h7 : _170_;
  assign _064_ = _123_ ? 1'h0 : 1'h1;
  assign _049_ = is_imm ? _064_ : _077_;
  assign _048_ = is_imm ? _063_ : 3'h7;
  assign _058_ = is_imm ? _073_ : _077_;
  assign _059_ = is_imm ? 1'h0 : _074_;
  assign _051_ = is_imm ? 1'h0 : _066_;
  assign _052_ = is_imm ? 1'h0 : _067_;
  assign _050_ = is_imm ? 1'h0 : _065_;
  assign _056_ = is_imm ? 1'h0 : _071_;
  assign _057_ = is_imm ? 1'h0 : _072_;
  assign _054_ = is_imm ? 1'h0 : _069_;
  assign _055_ = is_imm ? 1'h0 : _070_;
  assign _032_ = is_alu ? 1'h1 : _049_;
  assign _043_ = is_alu ? _148_ : _058_;
  assign _031_ = is_alu ? opcode[4:2] : _048_;
  assign _044_ = is_alu ? 1'h0 : _059_;
  assign _034_ = is_alu ? 1'h0 : _051_;
  assign _035_ = is_alu ? 1'h0 : _052_;
  assign _033_ = is_alu ? 1'h0 : _050_;
  assign _041_ = is_alu ? 1'h0 : _056_;
  assign _042_ = is_alu ? 1'h0 : _057_;
  assign _039_ = is_alu ? 1'h0 : _054_;
  assign _040_ = is_alu ? 1'h0 : _055_;
  assign _027_ = skip_flag ? 1'h0 : _044_;
  assign _017_ = skip_flag ? 1'h0 : _034_;
  assign _018_ = skip_flag ? 1'h0 : _035_;
  assign _016_ = skip_flag ? 1'h0 : _033_;
  assign _024_ = skip_flag ? 1'h0 : _041_;
  assign _025_ = skip_flag ? 1'h0 : _042_;
  assign _015_ = skip_flag ? 1'h0 : _032_;
  assign _022_ = skip_flag ? 1'h0 : _039_;
  assign _023_ = skip_flag ? 1'h0 : _040_;
  assign _014_ = skip_flag ? 3'h7 : _031_;
  assign _026_ = skip_flag ? 1'h0 : _043_;
  assign pc_inc = _114_ ? 1'h1 : 1'h0;
  assign ir_load0 = _156_ ? 1'h1 : 1'h0;
  function [0:0] _302_;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _302_ = b[0:0];
      3'b?1?:
        _302_ = b[1:1];
      3'b1??:
        _302_ = b[2:2];
      default:
        _302_ = a;
    endcase
  endfunction
  assign mem_rd = _302_(1'h0, { 1'h1, _019_, _076_ }, { _114_, _157_, _155_ });
  function [2:0] _303_;
    input [2:0] a;
    input [5:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _303_ = b[2:0];
      2'b1?:
        _303_ = b[5:3];
      default:
        _303_ = a;
    endcase
  endfunction
  assign addr_src = _303_(3'h0, { _013_, _053_ }, { _157_, _155_ });
  assign skip_set = _119_ ? _027_ : 1'h0;
  assign ie_clr = _119_ ? _017_ : 1'h0;
  assign ie_set = _119_ ? _018_ : 1'h0;
  assign halt_out = _119_ ? _016_ : 1'h0;
  assign ir_load1 = _119_ ? 1'h1 : 1'h0;
  function [0:0] _309_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _309_ = b[0:0];
      2'b1?:
        _309_ = b[1:1];
      default:
        _309_ = a;
    endcase
  endfunction
  assign sp_dec = _309_(1'h0, { _028_, _075_ }, { _157_, _155_ });
  function [0:0] _310_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _310_ = b[0:0];
      2'b1?:
        _310_ = b[1:1];
      default:
        _310_ = a;
    endcase
  endfunction
  assign sp_inc = _310_(1'h0, { _029_, _076_ }, { _157_, _155_ });
  assign ptr_dec = _119_ ? _024_ : 1'h0;
  function [0:0] _312_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _312_ = b[0:0];
      2'b1?:
        _312_ = b[1:1];
      default:
        _312_ = a;
    endcase
  endfunction
  assign ptr_inc = _312_(1'h0, { _025_, _011_ }, { _119_, _157_ });
  assign flags_we = _119_ ? _015_ : 1'h0;
  assign pc_branch = _119_ ? _022_ : 1'h0;
  function [0:0] _315_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _315_ = b[0:0];
      2'b1?:
        _315_ = b[1:1];
      default:
        _315_ = a;
    endcase
  endfunction
  assign pc_load = _315_(1'h0, { _023_, _075_ }, { _119_, _154_ });
  assign _154_ = state == 3'h4;
  assign alu_op = _119_ ? _014_ : 3'h7;
  function [0:0] _318_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _318_ = b[0:0];
      2'b1?:
        _318_ = b[1:1];
      default:
        _318_ = a;
    endcase
  endfunction
  assign mem_wr = _318_(1'h0, { _020_, _075_ }, { _157_, _155_ });
  function [0:0] _319_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _319_ = b[0:0];
      2'b1?:
        _319_ = b[1:1];
      default:
        _319_ = a;
    endcase
  endfunction
  assign reg_we = _319_(1'h0, { _026_, _096_ }, { _119_, _157_ });
  assign _101_ = is_jal ? 3'h4 : 3'h0;
  assign _091_ = is_ret ? 3'h3 : 3'h0;
  assign _081_ = is_jal ? 3'h3 : _091_;
  assign _038_ = _147_ ? 3'h2 : _053_;
  assign _021_ = _132_ ? 3'h2 : _038_;
  function [2:0] _325_;
    input [2:0] a;
    input [11:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _325_ = b[2:0];
      4'b??1?:
        _325_ = b[5:3];
      4'b?1??:
        _325_ = b[8:6];
      4'b1???:
        _325_ = b[11:9];
      default:
        _325_ = a;
    endcase
  endfunction
  assign next_state = _325_(3'h0, { 3'h1, _021_, _081_, _101_ }, { _156_, _119_, _157_, _155_ });
  assign _155_ = state == 3'h3;
  assign _157_ = state == 3'h2;
  assign _119_ = state == 3'h1;
  assign _156_ = ! state;
  assign _158_ = _127_ ? 1'h0 : 1'hx;
  assign _000_ = _126_ ? 1'h1 : _158_;
  function [0:0] _332_;
    input [0:0] a;
    input [7:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _332_ = b[0:0];
      8'b??????1?:
        _332_ = b[1:1];
      8'b?????1??:
        _332_ = b[2:2];
      8'b????1???:
        _332_ = b[3:3];
      8'b???1????:
        _332_ = b[4:4];
      8'b??1?????:
        _332_ = b[5:5];
      8'b?1??????:
        _332_ = b[6:6];
      8'b1???????:
        _332_ = b[7:7];
      default:
        _332_ = a;
    endcase
  endfunction
  assign branch_taken = _332_(1'hx, { flag_z, _151_, flag_c, _152_, flag_n, _153_, 2'h2 }, { _120_, _121_, _164_, _163_, _162_, _161_, _160_, _159_ });
  assign _159_ = opcode[4:2] == 3'h7;
  assign _160_ = opcode[4:2] == 3'h6;
  assign _161_ = opcode[4:2] == 3'h5;
  assign _162_ = opcode[4:2] == 3'h4;
  assign _163_ = opcode[4:2] == 3'h3;
  assign _164_ = opcode[4:2] == 3'h2;
  assign _121_ = opcode[4:2] == 3'h1;
  assign _120_ = ! opcode[4:2];
  assign _087_ = is_ret ? 1'h1 : 1'h0;
  assign _068_ = is_ret ? 3'h2 : 3'h0;
  assign _075_ = is_jal ? 1'h1 : 1'h0;
  assign _053_ = is_jal ? 3'h2 : _068_;
  assign _076_ = is_jal ? 1'h0 : _087_;
  assign _006_ = _137_ ? 1'h1 : 1'h0;
  assign _061_ = _137_ ? 1'h1 : _076_;
  assign _062_ = _137_ ? 3'h2 : _053_;
  assign _060_ = _137_ ? 1'h0 : _075_;
  assign _045_ = _136_ ? 1'h1 : _060_;
  assign _047_ = _136_ ? 3'h2 : _062_;
  assign _046_ = _136_ ? 1'h0 : _061_;
  assign _111_ = _136_ ? 1'h0 : _006_;
  assign _036_ = opcode[2] ? 1'h0 : 1'h1;
  assign _037_ = opcode[2] ? 1'h1 : 1'h0;
  function [2:0] _356_;
    input [2:0] a;
    input [5:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _356_ = b[2:0];
      2'b1?:
        _356_ = b[5:3];
      default:
        _356_ = a;
    endcase
  endfunction
  assign _030_ = _356_(3'h0, 6'h0a, { _113_, _165_ });
  assign _165_ = | { _162_, _161_ };
  assign _012_ = _166_ ? 1'h1 : 1'h0;
  assign _166_ = | { _164_, _163_ };
  assign _020_ = _135_ ? _037_ : _045_;
  assign _019_ = _135_ ? _036_ : _046_;
  assign _096_ = _135_ ? _036_ : _111_;
  assign _011_ = _135_ ? _012_ : 1'h0;
  assign _013_ = _135_ ? _030_ : _047_;
  assign _028_ = _135_ ? 1'h0 : _045_;
  assign _029_ = _135_ ? 1'h0 : _046_;
  assign _008_ = _167_ ? 1'h1 : 1'h0;
  assign _167_ = opcode == 8'hf3;
  assign _009_ = _168_ ? 1'h1 : 1'h0;
  assign _168_ = opcode == 8'hf2;
  assign _007_ = _169_ ? 1'h1 : 1'h0;
  assign _169_ = opcode == 8'hff;
  assign _002_ = is_system ? _008_ : 1'h0;
  assign _003_ = is_system ? _009_ : 1'h0;
  assign _001_ = is_system ? _007_ : 1'h0;
  assign _010_ = _121_ ? 1'h1 : 1'h0;
  assign _005_ = _120_ ? 1'h1 : 1'h0;
  assign _004_ = _120_ ? 1'h0 : _010_;
  assign _109_ = is_ptr ? _004_ : 1'h0;
  assign _110_ = is_ptr ? _005_ : 1'h0;
  assign _170_ = opcode[4:2] - 3'h6;
  assign skip_cond = _116_ ? flag_z : _171_;
  assign _171_ = _117_ ? _151_ : _172_;
  assign _172_ = _118_ ? flag_c : _152_;
  assign int_enter = 1'h0;
  assign op = opcode[4:2];
  assign reg_field = opcode[1:0];
  assign skip_active = skip_flag;
  assign state_out = state;
  assign unit = opcode[7:5];
endmodule

module rv8_cpu(clk, rst_n, nmi_n, irq_n, addr_bus, data_bus, mem_rd_n, mem_wr_n, halt, sync);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire [7:0] a0_out;
  output [15:0] addr_bus;
  wire [15:0] addr_bus;
  wire [15:0] addr_mux;
  wire [2:0] addr_src;
  wire [7:0] alu_a;
  wire [7:0] alu_b;
  wire alu_cout;
  wire alu_neg;
  wire [2:0] alu_op;
  wire [7:0] alu_result;
  wire alu_zero;
  input clk;
  wire clk;
  inout [7:0] data_bus;
  wire [7:0] data_bus;
  wire [7:0] data_in;
  wire data_oe;
  wire [7:0] data_out;
  reg flag_c;
  reg flag_ie;
  reg flag_n;
  reg flag_z;
  wire flags_we;
  output halt;
  wire halt;
  wire halt_out;
  wire ie_clr;
  wire ie_set;
  wire int_enter;
  wire ir_load0;
  wire ir_load1;
  reg [7:0] ir_opcode;
  reg [7:0] ir_operand;
  input irq_n;
  wire irq_n;
  wire mem_rd;
  output mem_rd_n;
  wire mem_rd_n;
  wire mem_wr;
  output mem_wr_n;
  wire mem_wr_n;
  input nmi_n;
  wire nmi_n;
  reg nmi_pending;
  reg nmi_prev;
  wire pc_branch;
  wire pc_inc;
  wire pc_load;
  wire [15:0] pc_out;
  wire [7:0] pg_out;
  wire [7:0] ph_out;
  wire [7:0] pl_out;
  wire ptr_dec;
  wire ptr_inc;
  wire [15:0] ptr_out;
  wire [7:0] reg_rd_data;
  wire reg_we;
  input rst_n;
  wire rst_n;
  wire skip_set;
  wire sp_dec;
  wire sp_inc;
  wire [7:0] sp_out;
  wire [2:0] state;
  output sync;
  wire sync;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ir_opcode <= 8'hfe;
    else if (ir_load0) ir_opcode <= data_bus;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ir_operand <= 8'h00;
    else if (ir_load1) ir_operand <= data_bus;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) nmi_pending <= 1'h0;
    else if (_03_) nmi_pending <= _02_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) flag_z <= 1'h0;
    else if (flags_we) flag_z <= alu_zero;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) flag_c <= 1'h0;
    else if (_04_) flag_c <= _00_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) flag_n <= 1'h0;
    else if (flags_we) flag_n <= alu_neg;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) flag_ie <= 1'h0;
    else if (_05_) flag_ie <= _01_;
  assign _03_ = | { _10_, int_enter };
  assign _04_ = | { _07_, _06_, flags_we };
  assign _05_ = | { ie_clr, ie_set };
  assign sync = ! state;
  assign _06_ = ir_opcode == 8'hf0;
  assign _07_ = ir_opcode == 8'hf1;
  assign _08_ = ir_opcode[2:0] == 3'h3;
  assign _09_ = ir_opcode[2:0] == 3'h4;
  assign _10_ = nmi_prev && _13_;
  assign _11_ = reg_we && _08_;
  assign _12_ = reg_we && _09_;
  assign _13_ = ! nmi_n;
  assign mem_rd_n = ~ mem_rd;
  assign mem_wr_n = ~ data_oe;
  assign _14_ = ~ irq_n;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) nmi_prev <= 1'h1;
    else nmi_prev <= nmi_n;
  assign _15_ = _10_ ? 1'h1 : 1'hx;
  assign _02_ = int_enter ? 1'h0 : _15_;
  assign _16_ = ie_set ? 1'h1 : 1'hx;
  assign _01_ = ie_clr ? 1'h0 : _16_;
  assign _17_ = flags_we ? alu_cout : 1'hx;
  assign _18_ = _06_ ? 1'h0 : _17_;
  assign _00_ = _07_ ? 1'h1 : _18_;
  function [15:0] _54_;
    input [15:0] a;
    input [79:0] b;
    input [4:0] s;
    casez (s) // synopsys parallel_case
      5'b????1:
        _54_ = b[15:0];
      5'b???1?:
        _54_ = b[31:16];
      5'b??1??:
        _54_ = b[47:32];
      5'b?1???:
        _54_ = b[63:48];
      5'b1????:
        _54_ = b[79:64];
      default:
        _54_ = a;
    endcase
  endfunction
  assign addr_bus = _54_(pc_out, { ptr_out, 8'h30, sp_out, 8'h00, ir_operand, pg_out, ir_operand, 8'hff, ir_operand }, { _23_, _22_, _21_, _20_, _19_ });
  assign _19_ = addr_src == 3'h5;
  assign _20_ = addr_src == 3'h4;
  assign _21_ = addr_src == 3'h3;
  assign _22_ = addr_src == 3'h2;
  assign _23_ = addr_src == 3'h1;
  assign data_bus = data_oe ? a0_out : 8'hzz;
  rv8_alu ALU (
    .a(a0_out),
    .b(alu_b),
    .carry_in(flag_c),
    .carry_out(alu_cout),
    .negative(alu_neg),
    .op(alu_op),
    .result(alu_result),
    .zero(alu_zero)
  );
  rv8_control CTRL (
    .addr_src(addr_src),
    .alu_op(alu_op),
    .clk(clk),
    .flag_c(flag_c),
    .flag_ie(flag_ie),
    .flag_n(flag_n),
    .flag_z(flag_z),
    .flags_we(flags_we),
    .halt_out(halt_out),
    .ie_clr(ie_clr),
    .ie_set(ie_set),
    .int_enter(int_enter),
    .ir_load0(ir_load0),
    .ir_load1(ir_load1),
    .irq_pending(_14_),
    .mem_rd(mem_rd),
    .mem_wr(data_oe),
    .nmi_pending(nmi_pending),
    .opcode(ir_opcode),
    .operand(ir_operand),
    .pc_branch(pc_branch),
    .pc_inc(pc_inc),
    .pc_load(pc_load),
    .ptr_dec(ptr_dec),
    .ptr_inc(ptr_inc),
    .reg_we(reg_we),
    .rst_n(rst_n),
    .skip_set(skip_set),
    .sp_dec(sp_dec),
    .sp_inc(sp_inc),
    .state_out(state)
  );
  rv8_pc PC (
    .branch(pc_branch),
    .clk(clk),
    .inc(pc_inc),
    .load(pc_load),
    .load_val(ptr_out),
    .offset(ir_operand),
    .pc(pc_out),
    .rst_n(rst_n)
  );
  rv8_pointer PTR (
    .clk(clk),
    .data_in(alu_result),
    .dec16(ptr_dec),
    .inc16(ptr_inc),
    .load_ph(_12_),
    .load_pl(_11_),
    .ph_out(ph_out),
    .pl_out(pl_out),
    .ptr_out(ptr_out),
    .rst_n(rst_n)
  );
  rv8_regfile REGS (
    .a0_out(a0_out),
    .clk(clk),
    .const_sel(ir_operand[3:2]),
    .pg_out(pg_out),
    .rd_data(alu_b),
    .rd_sel(ir_operand[2:0]),
    .rst_n(rst_n),
    .sp_out(sp_out),
    .we(reg_we),
    .wr_data(alu_result),
    .wr_sel(3'h2)
  );
  assign addr_mux = addr_bus;
  assign alu_a = a0_out;
  assign data_in = data_bus;
  assign data_out = a0_out;
  assign halt = halt_out;
  assign mem_wr = data_oe;
  assign reg_rd_data = alu_b;
endmodule

module rv8_pc(clk, rst_n, inc, load, branch, load_val, offset, pc);
  wire [15:0] _00_;
  wire [15:0] _01_;
  wire _02_;
  wire [15:0] _03_;
  wire [15:0] _04_;
  input branch;
  wire branch;
  wire [15:0] branch_target;
  input clk;
  wire clk;
  input inc;
  wire inc;
  input load;
  wire load;
  input [15:0] load_val;
  wire [15:0] load_val;
  input [7:0] offset;
  wire [7:0] offset;
  output [15:0] pc;
  reg [15:0] pc;
  input rst_n;
  wire rst_n;
  assign _01_ = pc + 16'h0001;
  assign branch_target = pc + { offset[7], offset[7], offset[7], offset[7], offset[7], offset[7], offset[7], offset[7], offset };
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pc <= 16'hfffc;
    else if (_02_) pc <= _00_;
  assign _02_ = | { branch, load, inc };
  assign _03_ = inc ? _01_ : 16'hxxxx;
  assign _04_ = branch ? branch_target : _03_;
  assign _00_ = load ? load_val : _04_;
endmodule

module rv8_pointer(clk, rst_n, load_pl, load_ph, inc16, dec16, data_in, ptr_out, pl_out, ph_out);
  wire [7:0] _00_;
  wire [15:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire [7:0] _08_;
  wire [7:0] _09_;
  wire [7:0] _10_;
  wire [7:0] _11_;
  wire [7:0] _12_;
  wire [7:0] _13_;
  wire [15:0] _14_;
  input clk;
  wire clk;
  input [7:0] data_in;
  wire [7:0] data_in;
  input dec16;
  wire dec16;
  input inc16;
  wire inc16;
  input load_ph;
  wire load_ph;
  input load_pl;
  wire load_pl;
  reg [7:0] ph;
  output [7:0] ph_out;
  wire [7:0] ph_out;
  reg [7:0] pl;
  output [7:0] pl_out;
  wire [7:0] pl_out;
  output [15:0] ptr_out;
  wire [15:0] ptr_out;
  input rst_n;
  wire rst_n;
  assign _01_ = { ph, pl } + 16'h0001;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pl <= 8'h00;
    else if (_05_) pl <= _00_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ph <= 8'h00;
    else if (_06_) ph <= _10_;
  assign _02_ = | { dec16, inc16, load_ph, load_pl };
  assign _03_ = { load_ph, load_pl } != 2'h2;
  assign _04_ = | { dec16, inc16, load_ph };
  assign _07_ = ~ load_pl;
  assign _05_ = & { _02_, _03_ };
  assign _06_ = & { _07_, _04_ };
  assign _08_ = dec16 ? _14_[15:8] : 8'hxx;
  assign _09_ = inc16 ? _01_[15:8] : _08_;
  assign _10_ = load_ph ? data_in : _09_;
  assign _11_ = dec16 ? _14_[7:0] : 8'hxx;
  assign _12_ = inc16 ? _01_[7:0] : _11_;
  assign _13_ = load_ph ? 8'hxx : _12_;
  assign _00_ = load_pl ? data_in : _13_;
  assign _14_ = { ph, pl } - 16'h0001;
  assign ph_out = ph;
  assign pl_out = pl;
  assign ptr_out = { ph, pl };
endmodule

module rv8_regfile(clk, rst_n, we, wr_sel, rd_sel, wr_data, rd_data, a0_out, sp_out, pg_out, const_sel);
  wire [7:0] _00_;
  wire [7:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  output [7:0] a0_out;
  wire [7:0] a0_out;
  input clk;
  wire clk;
  input [1:0] const_sel;
  wire [1:0] const_sel;
  wire [31:0] i;
  output [7:0] pg_out;
  wire [7:0] pg_out;
  output [7:0] rd_data;
  wire [7:0] rd_data;
  input [2:0] rd_sel;
  wire [2:0] rd_sel;
  reg [7:0] \regs[1] ;
  reg [7:0] \regs[2] ;
  reg [7:0] \regs[3] ;
  reg [7:0] \regs[4] ;
  reg [7:0] \regs[5] ;
  reg [7:0] \regs[6] ;
  input rst_n;
  wire rst_n;
  output [7:0] sp_out;
  wire [7:0] sp_out;
  input we;
  wire we;
  input [7:0] wr_data;
  wire [7:0] wr_data;
  input [2:0] wr_sel;
  wire [2:0] wr_sel;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \regs[2]  <= 8'h00;
    else if (_02_) \regs[2]  <= wr_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \regs[3]  <= 8'h00;
    else if (_03_) \regs[3]  <= wr_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \regs[4]  <= 8'h00;
    else if (_04_) \regs[4]  <= wr_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \regs[5]  <= 8'h00;
    else if (_05_) \regs[5]  <= wr_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \regs[6]  <= 8'h00;
    else if (_06_) \regs[6]  <= wr_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \regs[1]  <= 8'h00;
    else if (_07_) \regs[1]  <= wr_data;
  assign _02_ = & { _15_, _09_ };
  assign _03_ = & { _14_, _09_ };
  assign _04_ = & { _13_, _09_ };
  assign _05_ = & { _12_, _09_ };
  assign _06_ = & { _11_, _09_ };
  assign _07_ = & { _16_, _09_ };
  assign _09_ = we && _10_;
  assign _10_ = | wr_sel;
  assign _11_ = wr_sel == 3'h6;
  assign _12_ = wr_sel == 3'h5;
  assign _13_ = wr_sel == 3'h4;
  assign _14_ = wr_sel == 3'h3;
  assign _15_ = wr_sel == 3'h2;
  assign _16_ = wr_sel == 3'h1;
  function [7:0] _47_;
    input [7:0] a;
    input [47:0] b;
    input [5:0] s;
    casez (s) // synopsys parallel_case
      6'b?????1:
        _47_ = b[7:0];
      6'b????1?:
        _47_ = b[15:8];
      6'b???1??:
        _47_ = b[23:16];
      6'b??1???:
        _47_ = b[31:24];
      6'b?1????:
        _47_ = b[39:32];
      6'b1?????:
        _47_ = b[47:40];
      default:
        _47_ = a;
    endcase
  endfunction
  assign _00_ = _47_(8'hxx, { \regs[1] , \regs[2] , \regs[3] , \regs[4] , \regs[5] , \regs[6]  }, { _22_, _21_, _20_, _19_, _18_, _17_ });
  assign _17_ = rd_sel == 3'h6;
  assign _18_ = rd_sel == 3'h5;
  assign _19_ = rd_sel == 3'h4;
  assign _20_ = rd_sel == 3'h3;
  assign _21_ = rd_sel == 3'h2;
  assign _22_ = rd_sel == 3'h1;
  assign _08_ = ! rd_sel;
  function [7:0] _55_;
    input [7:0] a;
    input [31:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _55_ = b[7:0];
      4'b??1?:
        _55_ = b[15:8];
      4'b?1??:
        _55_ = b[23:16];
      4'b1???:
        _55_ = b[31:24];
      default:
        _55_ = a;
    endcase
  endfunction
  assign _01_ = _55_(8'hxx, 32'd130944, { _26_, _25_, _24_, _23_ });
  assign _23_ = const_sel == 2'h3;
  assign _24_ = const_sel == 2'h2;
  assign _25_ = const_sel == 2'h1;
  assign _26_ = ! const_sel;
  assign rd_data = _08_ ? _01_ : _00_;
  assign a0_out = \regs[2] ;
  assign i = 32'd7;
  assign pg_out = \regs[6] ;
  assign sp_out = \regs[1] ;
endmodule
